### ISSUE TITLE
Players experience is being set to 999 levels on game end.

### ISSUE THREAD

**Issue by mibby** [Shynixn/BlockBall#9]
BlockBall v3.8.0

When the game ends and players are brought back to the main hub world, their level is set to 999.

**Comment by Shynixn** [comment]
Thanks for reporting, checking it.

**Comment by Shynixn** [comment]
Should be fixed in the latest snapshot. 
_blockball-3.8.1-20170303.142405-2.jar_

**Comment by mibby** [comment]
Apologies for the late response. Using the new dev build with this commit https://github.com/Shynixn/BlockBall/commit/ef54b62d6a6d54b6d0f44576bceef4b8a2b6f298, the problem still exists and actually instead breaks other things.

Joining the BlockBall lounge in a separate world, it flashes the level count to 999 then disappears entirely when a second player joins. No countdown until the game force starts is shown whatsoever. I believe there was no countdown because I had the ```min-size: 2``` set so it would require 4 players to start the game. Lowering it to 1, level count gets set to 999 and then counts down from 60 as soon as the second player joins the lounge.

When leaving the lounge via exit sign available inside the lounge and on game end due to score being met, players levels are still being set to 999 when brought back to the main hub world.

**Comment by Shynixn** [comment]
I see, hopefully I'm able to release a new dev build in the next time as it even takes me a week to reply to issues.

**Comment by mibby** [comment]
All good. I'll be available to test whenever you do begin to push out newer commits.

**Comment by Shynixn** [comment]
* Removed displaying 999 before the countdown starts
